# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaemonHound < Formula
  desc "Opinionated local config and secret management for developers"
  homepage "https://github.com/0xdps/daemon-hound"
  version "1.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xdps/daemon-hound/releases/download/v1.1.0/daemon-hound_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "d717d87db31bae28cd76828980d40247969337d4ed9188fa5cb346fd0772cbad"

      define_method(:install) do
        bin.install "dhd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xdps/daemon-hound/releases/download/v1.1.0/daemon-hound_1.1.0_Darwin_arm64.tar.gz"
      sha256 "fdb323d280c8407479ba06aa572a27045118d549e7bd09162f856da0a87905d5"

      define_method(:install) do
        bin.install "dhd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xdps/daemon-hound/releases/download/v1.1.0/daemon-hound_1.1.0_Linux_x86_64.tar.gz"
      sha256 "307214cdcede0c56fd15608da15763efaad57ed0d308d93ba2afeace7f8ccc29"
      define_method(:install) do
        bin.install "dhd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xdps/daemon-hound/releases/download/v1.1.0/daemon-hound_1.1.0_Linux_arm64.tar.gz"
      sha256 "1a0920370da8fbf1ce9490aecd6c8342074f9d9435acc2f986e3218f2cc32b7f"
      define_method(:install) do
        bin.install "dhd"
      end
    end
  end

  test do
    system "#{bin}/dhd", "--version"
  end
end
